name: rpi_client_gtk_c_checker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: autogen
      run: |
        cd rpiclient
        ./autogen.sh
    - name: make
      run: |
        cd rpiclient
        make
    - name: make check
      run: |
        cd rpiclient
        make check
    - name: make distcheck
      run: |
        cd rpiclient
        make distcheck
